# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'DKProject' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DKProject
  
  pod 'AFNetworking', '~> 3.2.1'
  
  pod 'YTKNetwork', '~> 2.0.4'

  pod 'YYModel', '~> 1.0.4'

  pod 'SDWebImage', '~> 4.4.2'

  pod 'Masonry', '~> 1.1.0'

end
